### PR TITLE
Update post, fix minor typo

### PR DESCRIPTION
**Pull request by pedramardakani**
Fix minor typo in the 'index.md' homepage.

Add footnotes in 'presentations/2022/Working_in_Command-Line_Interface.md' and change the link names.

### CODE REVIEW

**Comment by pedramardakani** [comment]
Thank you @smhr for creating the OAM page ✌ Here are just a few small changes, I hope it builds easily.

**Comment by smhr** [comment]
Thank you @pedramardakani for your fixes.

**Comment by pedramardakani** [comment]
Oh I missed a semicolon while creating the footnotes[^1]! I'm just following `github` markdown syntax but I don't know if it works in `jekyll` as well. Do you mind checking the new commit as well?

[^1]: It works in `github` 🤔

**Comment by smhr** [comment]
The new commit should correct the footnotes. I will merge it. Thank you.

**Pull request merged**
